// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KZQpJWhzoSRb33O9Ms3hulNuweXiNVY',
    appId: '1:1085725881002:web:5f9b9a16c83165ce0796d3',
    messagingSenderId: '1085725881002',
    projectId: 'eleeye-15421',
    authDomain: 'eleeye-15421.firebaseapp.com',
    storageBucket: 'eleeye-15421.firebasestorage.app',
    measurementId: 'G-M0QB5SV7TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXCpvHik8Dg67x1Z186NuJQJexgi-w0U',
    appId: '1:1085725881002:android:d441266b34184d5a0796d3',
    messagingSenderId: '1085725881002',
    projectId: 'eleeye-15421',
    storageBucket: 'eleeye-15421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4Ob_KAjrBEISmHKbQpmoCUKRNw3CROE',
    appId: '1:1085725881002:ios:a1d4d98db64382fe0796d3',
    messagingSenderId: '1085725881002',
    projectId: 'eleeye-15421',
    storageBucket: 'eleeye-15421.firebasestorage.app',
    iosBundleId: 'com.mobile-frontend.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4Ob_KAjrBEISmHKbQpmoCUKRNw3CROE',
    appId: '1:1085725881002:ios:56c60659feae15bf0796d3',
    messagingSenderId: '1085725881002',
    projectId: 'eleeye-15421',
    storageBucket: 'eleeye-15421.firebasestorage.app',
    iosBundleId: 'com.example.eleeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1KZQpJWhzoSRb33O9Ms3hulNuweXiNVY',
    appId: '1:1085725881002:web:5adf47c43079ea870796d3',
    messagingSenderId: '1085725881002',
    projectId: 'eleeye-15421',
    authDomain: 'eleeye-15421.firebaseapp.com',
    storageBucket: 'eleeye-15421.firebasestorage.app',
    measurementId: 'G-7FHCKXQWDL',
  );
}
