// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tgek2q53zLlYJjXTf-RqkgM0dPcOY5I',
    appId: '1:255134296378:web:70253997072c60ac3b4803',
    messagingSenderId: '255134296378',
    projectId: 'eleeye-88644',
    authDomain: 'eleeye-88644.firebaseapp.com',
    storageBucket: 'eleeye-88644.firebasestorage.app',
    measurementId: 'G-HHMD064C2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInk_bynVu_K7WO3FPkqaBA8ZPEcuRt20',
    appId: '1:255134296378:android:c2a91dd128726cb63b4803',
    messagingSenderId: '255134296378',
    projectId: 'eleeye-88644',
    storageBucket: 'eleeye-88644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMbCxsXyTihwDHpuv-WMq7AnO5N6S5LM',
    appId: '1:255134296378:ios:2420cc59703a86363b4803',
    messagingSenderId: '255134296378',
    projectId: 'eleeye-88644',
    storageBucket: 'eleeye-88644.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMbCxsXyTihwDHpuv-WMq7AnO5N6S5LM',
    appId: '1:255134296378:ios:2420cc59703a86363b4803',
    messagingSenderId: '255134296378',
    projectId: 'eleeye-88644',
    storageBucket: 'eleeye-88644.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4tgek2q53zLlYJjXTf-RqkgM0dPcOY5I',
    appId: '1:255134296378:web:c386b2ac24580be33b4803',
    messagingSenderId: '255134296378',
    projectId: 'eleeye-88644',
    authDomain: 'eleeye-88644.firebaseapp.com',
    storageBucket: 'eleeye-88644.firebasestorage.app',
    measurementId: 'G-M66GPDR0BF',
  );
}
